services:
  - type: web
    name: flask-app
    plan: free
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "bash start.sh"

  - type: worker
    name: celery-worker
    plan: free
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python -m celery -A app.celery worker --loglevel=info"

